# Generated by Django 5.2.15 on 2026-06-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail Financeiro')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Comercial')),
                ('contato', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pessoa de Contato')),
            ],
        ),
        migrations.CreateModel(
            name='ColetaImpressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('serial', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número de Série')),
                ('contador_geral', models.IntegerField(blank=True, null=True, verbose_name='Contador Geral')),
                ('uptime', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tempo de Atividade (Uptime)')),
                ('mensagem_painel', models.TextField(blank=True, null=True, verbose_name='Mensagem do Painel')),
                ('porcentagem_toner', models.FloatField(blank=True, null=True, verbose_name='Porcentagem de Toner')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('data_coleta', models.DateTimeField(auto_now=True, verbose_name='Data da Coleta')),
                ('modelo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo da Impressora')),
                ('contador_total', models.IntegerField(blank=True, null=True, verbose_name='Contador Total')),
                ('contador_a4', models.IntegerField(blank=True, null=True, verbose_name='Contador A4')),
                ('contador_a3', models.IntegerField(blank=True, null=True, verbose_name='Contador A3')),
                ('contador_a5', models.IntegerField(blank=True, null=True, verbose_name='Contador A5')),
                ('tinta_preta', models.FloatField(blank=True, null=True, verbose_name='Porcentagem Tinta Preta')),
                ('tinta_ciano', models.FloatField(blank=True, null=True, verbose_name='Porcentagem Tinta Ciano')),
                ('tinta_magenta', models.FloatField(blank=True, null=True, verbose_name='Porcentagem Tinta Magenta')),
                ('tinta_amarela', models.FloatField(blank=True, null=True, verbose_name='Porcentagem Tinta Amarela')),
                ('caixa_manutencao', models.FloatField(blank=True, null=True, verbose_name='Porcentagem Caixa de Manutenção')),
            ],
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_chave', models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Chave do Token')),
                ('nome_identificador', models.CharField(max_length=255, verbose_name='Nome Identificador')),
                ('tipo_acesso', models.CharField(choices=[('oids_only', 'Apenas Coleta de OIDs'), ('metrics_write', 'Apenas Escrita de Métricas/Telemetria'), ('logs_alerts', 'Apenas Logs e Alertas'), ('full_access', 'Acesso Total / Administrador')], max_length=50, verbose_name='Tipo de Acesso / Permissão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='core.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('serial_number', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Número de Série')),
                ('nome_comercial', models.CharField(max_length=255, verbose_name='Nome Comercial')),
                ('modelo', models.CharField(max_length=150, verbose_name='Modelo do Equipamento')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('status_sistema', models.CharField(default='Ativo', max_length=50, verbose_name='Status no Sistema')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impressoras', to='core.brand', verbose_name='Marca')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressoras', to='core.cliente', verbose_name='Cliente Responsável')),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
                'db_table': 'impressora',
            },
        ),
        migrations.CreateModel(
            name='PrinterOID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_serial_number', models.CharField(max_length=255, verbose_name='OID Número de Série')),
                ('oid_counter_total', models.CharField(max_length=255, verbose_name='OID Contador Geral')),
                ('oid_counter_mono', models.CharField(max_length=255, verbose_name='OID Contador Mono')),
                ('oid_counter_color', models.CharField(max_length=255, verbose_name='OID Contador Color')),
                ('oid_toner_level', models.CharField(max_length=255, verbose_name='OID Nível de Toner')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oids', to='core.brand', verbose_name='Marca Vinculada')),
            ],
            options={
                'verbose_name': 'Configuração de OID',
                'verbose_name_plural': 'Configurações de OID',
                'db_table': 'printer_oid',
            },
        ),
    ]
