# Generated by Django 5.2.15 on 2026-06-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='contador_inicial',
            field=models.IntegerField(default=0, verbose_name='Contador Inicial'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Impressora'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='status',
            field=models.CharField(choices=[('Disponível no Estoque', 'Disponível no Estoque'), ('Ativa', 'Ativa')], default='Disponível no Estoque', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado Em'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressoras', to='core.cliente', verbose_name='Cliente Responsável'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='modelo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Modelo do Equipamento'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='nome_comercial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Comercial'),
        ),
    ]
