# Generated by Django 5.2.15 on 2026-06-30 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_impressora_contador_inicial_impressora_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printeroid',
            options={'verbose_name': 'Configuração de OID da Marca', 'verbose_name_plural': 'Configurações de OID das Marcas'},
        ),
        migrations.AddField(
            model_name='printeroid',
            name='oid_caixa_manutencao',
            field=models.CharField(default='1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.5', max_length=255, verbose_name='OID Caixa Manutenção'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='oid_mensagem_painel',
            field=models.CharField(default='1.3.6.1.2.1.43.16.5.1.2.1.1', max_length=255, verbose_name='OID Mensagem de Painel'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='oid_tempo_ligada',
            field=models.CharField(default='1.3.6.1.2.1.1.3.0', max_length=255, verbose_name='OID Tempo Ligada (Uptime)'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='oid_tinta_amarela',
            field=models.CharField(default='1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.4', max_length=255, verbose_name='OID Tinta Amarela'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='oid_tinta_ciano',
            field=models.CharField(default='1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.2', max_length=255, verbose_name='OID Tinta Ciano'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='oid_tinta_magenta',
            field=models.CharField(default='1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.3', max_length=255, verbose_name='OID Tinta Magenta'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='oid_tinta_preta',
            field=models.CharField(default='1.3.6.1.4.1.1248.1.2.2.28.1.1.2.1.1', max_length=255, verbose_name='OID Tinta Preta'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='oid_toner_full',
            field=models.CharField(default='1.3.6.1.2.1.43.11.1.1.8.1.1', max_length=255, verbose_name='OID Toner Cheio (Full)'),
        ),
        migrations.AlterField(
            model_name='printeroid',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oid_config', to='core.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='printeroid',
            name='oid_counter_color',
            field=models.CharField(default='1.3.6.1.4.1.1248.1.2.2.6.1.1.4.1.1', max_length=255, verbose_name='OID Contador Color / A3'),
        ),
        migrations.AlterField(
            model_name='printeroid',
            name='oid_counter_mono',
            field=models.CharField(default='1.3.6.1.4.1.1248.1.2.2.6.1.1.4.1.2', max_length=255, verbose_name='OID Contador Mono / A4'),
        ),
        migrations.AlterField(
            model_name='printeroid',
            name='oid_counter_total',
            field=models.CharField(default='1.3.6.1.2.1.43.10.2.1.4.1.1', max_length=255, verbose_name='OID Contador Geral / Total'),
        ),
        migrations.AlterField(
            model_name='printeroid',
            name='oid_serial_number',
            field=models.CharField(default='1.3.6.1.2.1.43.5.1.1.17.1', max_length=255, verbose_name='OID Número de Série'),
        ),
        migrations.AlterField(
            model_name='printeroid',
            name='oid_toner_level',
            field=models.CharField(default='1.3.6.1.2.1.43.11.1.1.9.1.1', max_length=255, verbose_name='OID Toner Atual (ou Nível Geral)'),
        ),
    ]
