# Generated by Django 5.2.15 on 2026-07-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_printeroid_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='oid_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressoras', to='core.printeroid', verbose_name='Perfil / Grupo de OID'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='is_color',
            field=models.BooleanField(default=True, verbose_name='Impressora Colorida'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='is_plotter',
            field=models.BooleanField(default=False, verbose_name='É Plotter (Oculta subcontadores A4/A3)'),
        ),
        migrations.AddField(
            model_name='printeroid',
            name='name',
            field=models.CharField(default='Padrão', max_length=255, verbose_name='Nome do Perfil / Grupo de OID'),
        ),
        migrations.AlterField(
            model_name='printeroid',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oid_profiles', to='core.brand', verbose_name='Marca'),
        ),
    ]
