# Generated by Django 5.2.16 on 2026-07-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_impressora_oid_profile_printeroid_is_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printeroid',
            name='printer_oid',
            field=models.CharField(blank=True, default='1.3.6.1.2.1.1.2.0', max_length=255, null=True, verbose_name='OID Identificadora da Impressora'),
        ),
    ]
