# Generated by Django 5.2.16 on 2026-07-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_printeroid_printer_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='printeroid',
            name='multiple_sizes',
            field=models.BooleanField(default=False, verbose_name='Múltiplos Tamanhos (A3/A4)'),
        ),
    ]
