# Generated by Django 5.2.16 on 2026-07-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_printeroid_multiple_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='printeroid',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='compatible_oid_profiles', to='core.brand', verbose_name='Marcas Compatíveis Adicionais'),
        ),
        migrations.AlterField(
            model_name='printeroid',
            name='printer_oid',
            field=models.CharField(default='1.3.6.1.2.1.1.2.0', max_length=255, verbose_name='OID Identificadora do Modelo'),
        ),
    ]
