# Generated by Django 5.2.16 on 2026-07-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_printeroid_brands_alter_printeroid_printer_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='data_alocacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Alocação'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='status',
            field=models.CharField(choices=[('ESTOQUE', 'Disponível no Estoque'), ('ALOCADA', 'Alocada em Cliente'), ('MANUTENÇÃO', 'Em Manutenção')], default='ESTOQUE', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.impressora', verbose_name='Impressora')),
            ],
            options={
                'verbose_name': 'Histórico de Manutenção',
                'verbose_name_plural': 'Históricos de Manutenção',
                'db_table': 'historico_manutencao',
            },
        ),
    ]
