# Generated by Django 5.2.16 on 2026-07-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_impressora_data_alocacao_alter_impressora_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail de Contato'),
        ),
    ]
