# Generated by Django 5.2.16 on 2026-07-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputadorAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_unico', models.CharField(max_length=255, unique=True, verbose_name='Identificador Único (UUID/Token)')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
            ],
            options={
                'verbose_name': 'Computador Agente',
                'verbose_name_plural': 'Computadores Agentes',
                'db_table': 'computador_agente',
            },
        ),
        migrations.AddField(
            model_name='impressora',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='ip_ou_hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP ou Hostname'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='computador_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressoras_vinculadas', to='core.computadoragente', verbose_name='Computador Agente'),
        ),
    ]
