# Generated by Django 5.2.16 on 2026-07-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_computadoragente_impressora_ativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadoragente',
            name='nome_cliente',
        ),
        migrations.AddField(
            model_name='computadoragente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computadores_agentes', to='core.cliente', verbose_name='Cliente Associado'),
        ),
    ]
