# Generated by Django 6.0.7 on 2026-07-20 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_computadoragente_nome_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='ultimo_contador_color',
            field=models.IntegerField(default=0, verbose_name='Último Contador Color'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='ultimo_contador_pb',
            field=models.IntegerField(default=0, verbose_name='Último Contador PB'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressoras', to='core.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='status',
            field=models.CharField(choices=[('ESTOQUE', 'Estoque'), ('CLIENTE', 'Cliente'), ('MANUTENCAO', 'Manutenção')], default='ESTOQUE', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='HistoricoContador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateField(verbose_name='Data da Coleta')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('contador_pb', models.IntegerField(default=0, verbose_name='Contador PB')),
                ('contador_color', models.IntegerField(default=0, verbose_name='Contador Color')),
                ('origem', models.CharField(choices=[('DIARIO', 'Diário'), ('MOVIMENTACAO', 'Movimentação')], default='DIARIO', max_length=20, verbose_name='Origem do Registro')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_contador', to='core.impressora', verbose_name='Impressora')),
            ],
            options={
                'verbose_name': 'Histórico de Contador',
                'verbose_name_plural': 'Históricos de Contadores',
                'db_table': 'historico_contador',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ESTOQUE', 'Estoque'), ('CLIENTE', 'Cliente'), ('MANUTENCAO', 'Manutenção')], max_length=50, verbose_name='Status')),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Movimentação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_movimentacao', to='core.cliente', verbose_name='Cliente')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_movimentacao', to='core.impressora', verbose_name='Impressora')),
            ],
            options={
                'verbose_name': 'Histórico de Movimentação',
                'verbose_name_plural': 'Históricos de Movimentações',
                'db_table': 'historico_movimentacao',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
