# Generated by Django 5.0 on 2026-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_impressora_ultimo_contador_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocontador',
            name='contador_a3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contador A3'),
        ),
        migrations.AddField(
            model_name='historicocontador',
            name='contador_a4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contador A4'),
        ),
        migrations.AddField(
            model_name='historicocontador',
            name='contador_a5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contador A5'),
        ),
        migrations.AddField(
            model_name='historicocontador',
            name='contador_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contador Total'),
        ),
    ]
